"""The brAInny ASCII banner — a plain braille render of the brain
icon (assets/icon.png, no wordmark baked in) via ascii-image-converter
(https://github.com/TheZoraiz/ascii-image-converter,
`ascii-image-converter assets/icon.png -b -H 26`). Single flat pink
when color is enabled; the actual `brAInny` wordmark below it is real
text, not derived from any image, so it stays crisp and lets "AI" get
its own color reliably.

Shown on bare `brainny` / `brainny --help`. Color is skipped for non-TTY
output or when NO_COLOR is set, per https://no-color.org.

Regenerating: if assets/icon.png changes, _GLYPH below must be
regenerated by hand with the command above — it is not read from
the image at runtime.
"""


from __future__ import annotations

import os
import sys

from brainny._version import get_version

__version__ = get_version()

RESET = "\033[0m"
BOLD = "\033[1m"
DIM = "\033[2m"
GOLD = "\033[93m"
PINK = "\033[38;5;211m"

_GLYPH = """\
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣤⣴⣶⣶⣿⣿⠿⠿⣿⣿⣿⣿⣶⣶⣦⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣶⣿⣿⣿⡿⠛⢉⣁⣤⣤⣤⣤⣤⣄⣈⠙⠻⢿⠿⠿⠿⠿⣿⣶⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣴⣿⡿⠿⠿⢿⠟⢁⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⠿⠋⣀⣠⣤⣤⣤⣤⣤⣈⠉⠻⢿⣦⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⣠⡾⠋⢁⣠⣤⣤⣤⣤⣄⡈⠛⢿⣿⡿⠋⣹⣿⣿⡟⠁⣠⣾⣿⣿⡿⢿⣿⣿⡿⠻⢿⣦⣄⠙⢿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⣠⡾⠃⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣦⡀⠛⠁⣼⣿⣿⠏⢠⣾⣿⣿⣿⡿⠃⣸⣿⣿⣇⠰⡄⢻⣿⣦⠈⢿⣿⣷⣄⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢀⣾⡟⢀⣾⣿⣿⣿⠛⢉⣉⠉⠻⣿⣿⣿⣿⠀⣼⣿⣿⡟⢀⣿⣿⣿⡿⠋⣀⣴⣿⠿⠿⢿⣦⣄⢺⣿⣿⣧⠈⢿⣿⣿⣷⡀⠀⠀⠀⠀
⠀⠀⠀⣠⣿⣿⠁⣼⣿⣿⣿⡇⢰⣿⣿⣷⡀⢻⣿⣿⡇⢰⣿⣿⣿⠁⣼⣿⣿⣿⠁⣴⣿⣿⣿⡆⠰⣤⠘⣿⡄⠛⢉⣠⣤⣤⣈⠙⢿⣿⣄⠀⠀⠀
⠀⠀⣰⣿⣿⡏⠀⠋⢉⣉⠉⠁⠘⣿⣿⣿⣷⣄⠙⠻⠁⣼⣿⣿⣿⠀⣿⣿⣿⣿⠀⣿⣿⣿⣿⣿⣦⣌⣀⠙⣷⠀⣾⣿⣿⣿⣿⣷⡀⢻⣿⣆⠀⠀
⠀⢠⣿⡿⠉⣠⣶⣿⣿⣿⣿⣿⣦⡈⢻⣿⣿⣿⣷⣄⠀⢿⣿⣿⣿⠀⣿⣿⣿⣿⠀⣿⣿⣿⣿⠉⣿⣿⣿⣷⠈⠀⣿⠟⠉⠉⠉⣹⣷⠀⣿⣿⡄⠀
⠀⣿⡏⢀⣾⣿⣿⣿⠿⠿⠿⣿⣿⠇⢸⣿⡿⢿⣿⣿⡆⢸⣿⣿⣿⣿⣿⣿⣿⠇⢰⣿⣿⠟⠁⣰⡿⠻⣿⣿⡇⠸⠋⣀⣀⣀⣴⣿⣿⠀⣿⣿⣿⠀
⢸⣿⠀⣾⣿⣿⡿⠁⣤⣶⣦⣤⣤⣴⣿⣿⡇⢸⣿⣿⣷⣼⣿⣿⣿⡿⠛⠉⣁⣠⣤⣤⣤⣴⣾⣿⠀⡆⢹⡿⠀⣰⣿⣿⣿⣿⣿⣿⠏⠀⠻⣿⣿⡇
⣾⡇⠀⣿⣿⣿⡇⢸⣿⣿⣿⣿⣿⣿⣿⣿⠃⣸⣿⣿⣿⣿⡿⠟⢁⣠⣾⣿⣿⣿⠿⣿⣿⣿⣿⣿⡄⣠⠟⢁⣼⣿⣿⡇⣿⣿⣿⣇⣠⣿⡄⠹⣿⣷
⣿⣿⠀⢿⣿⣿⣷⡀⠻⢿⣿⣿⣿⣿⠿⠃⠀⠛⢉⣁⣠⣤⣤⣶⣿⣿⣿⣿⣿⠏⣰⣿⣿⣿⡿⠏⠀⢁⣴⣿⣿⣿⡿⠀⠛⣛⡛⠻⠿⣿⣿⠀⢿⣿
⣿⣿⣇⠘⢿⣿⣿⣿⣦⣄⣈⣉⣉⣠⡤⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⠟⠋⢁⣀⣁⣀⣀⠀⠠⢴⣾⣿⣿⣿⣿⠏⢠⣶⣿⣿⣿⡄⠀⢸⣿⠇⢸⣿
⢿⣿⣿⣧⡀⠙⢿⣿⣿⣿⣿⣿⣿⣿⠁⣼⣿⣿⣿⣿⡿⠛⠛⠋⣉⣠⣴⣾⣿⣿⣿⣿⣿⣿⣶⣤⣉⣉⣻⣿⠏⠀⣉⡅⠠⠀⠙⣿⣷⣾⣿⠀⣾⡿
⢸⣿⣿⣿⣿⣶⣤⣈⡉⠛⠛⠛⠋⠁⢰⣿⣿⣿⡿⠃⣠⣶⣿⣿⣿⣿⡿⠟⠋⣁⣀⣤⣿⣿⣿⣿⣿⣿⣿⡟⢠⣾⣿⣿⣦⣤⣤⣾⣿⣿⠃⣰⣿⡇
⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠸⣿⣿⣿⣇⣸⣿⣿⡿⠿⠛⠉⣠⣴⣿⣿⣿⠿⠟⠛⠋⢉⣉⣩⡟⢀⣾⠛⠻⠿⣿⣿⣿⠿⠛⢁⣴⣿⣿⠀
⠀⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡀⠻⣿⣿⣿⣿⣿⣿⣷⣴⣶⣿⣿⡿⠛⠉⠠⣴⣶⣿⣿⣿⡿⠋⢠⣾⣿⣷⣶⣦⣤⣤⠀⣴⣾⣿⣿⣿⠃⠀
⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣄⠙⠻⣿⣿⣿⣿⣿⡿⠿⠛⢁⣤⣶⣿⣆⠘⢿⣿⠟⠉⠀⠶⠿⠟⣁⣤⡈⢙⣿⡏⢠⣿⣿⣿⣿⠏⠀⠀
⠀⠀⠀⠙⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⣤⣀⣉⣁⣠⣤⣶⣦⠈⢿⣿⣿⣿⡇⠘⢁⣴⣾⣿⣶⣶⣤⣈⣁⣴⣾⠟⢀⣾⣿⣿⣿⠋⠀⠀⠀
⠀⠀⠀⠀⠈⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⡉⠻⣿⣿⠀⣾⣿⣿⣿⣿⣿⣿⣿⠿⠛⢁⣴⣿⣿⣿⡿⠁⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⡈⠻⠀⣿⣿⡟⢁⣤⣤⣤⣤⣴⣶⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄⠀⣿⣿⡇⢸⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄⢸⣿⣇⠘⣿⣿⣿⣿⣿⠟⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⠀⣿⣿⡀⢻⠿⠛⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠛⠻⠿⠿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠿⠂⠘⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\
"""


def _color_enabled() -> bool:
    if os.environ.get("NO_COLOR") is not None:
        return False
    return sys.stdout.isatty()


def render_banner() -> str:
    if _color_enabled():
        glyph = f"{PINK}{_GLYPH}{RESET}"
        wordmark = f"   {BOLD}br{GOLD}AI{RESET}{BOLD}nny{RESET}  v{__version__}"
        tagline = f"   {DIM}catches your ideas before the wind{RESET}"
    else:
        glyph = _GLYPH
        wordmark = f"   brAInny  v{__version__}"
        tagline = "   catches your ideas before the wind"

    return glyph + "\n\n" + wordmark + "\n" + tagline + "\n"
